const PRIMARY_COLOR = '#54B247';
const PRIMARY_COLOR_DISABLE = '#D3FBCE';

const PRIMARY_RED_COLOR = '#DC4545'
const RED_COLOR = '#FFC0C0';
const PRIMARY_BLUE_COLOR = '#6BA0D8'
const BLUE_COLOR = '#BDDEFF'
const PRIMARY_PURPLE_COLOR = '#996FD0'
const PURPLE_COLOR = '#DCC1FF'
const WHITE_COLOR = '#FFFFFF'
const PRIMARY_ORANGE_COLOR = '#E98F08'
const ORANGE_COLOR = '#FFE2B7'

const FONT_INACTIVE = '#C6C6C6';
const FONT_ACTIVE = '#515A50';

export {
    PRIMARY_COLOR,
    PRIMARY_COLOR_DISABLE,
    PRIMARY_RED_COLOR,
    RED_COLOR,
    PRIMARY_BLUE_COLOR,
    BLUE_COLOR,
    PRIMARY_PURPLE_COLOR,
    PURPLE_COLOR,
    WHITE_COLOR,
    PRIMARY_ORANGE_COLOR,
    ORANGE_COLOR,
    FONT_INACTIVE,
    FONT_ACTIVE,
};